### ISSUE TITLE
StyleGuide: Examples should start with good, end with bad

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/duckduckhack-docs#57]
We should start the good vs bad examples (in the style guide) with good first, then bad. I've seen a few style guides use the suggested format and it reads better (IMO); as well as ensuring the readers see the good version first (first impressions guys)!

/cc @talsraviv

**Comment by moollaza** [comment]
Not sure I agree -- AirBnb is well know for their style guide and it follows the same format as ours: https://github.com/airbnb/javascript

When skimming, you can look at the bottom of the code blocks to see what is expected.

IMO if you look at the good first, then all the bad, you'll move on with the bad examples in your head because that's what you saw last.

There's pros and cons to both layouts but I'd argue we should keep it as is for the sake of avoiding unnecessary work

**Comment by GuiltyDolphin** [comment]
@moollaza Hmm, my point is the opposite ;) look at the good and look no further!

However, yes - that did cross my mind (last thing in your head is the bad).

@talsraviv Do you agree with @moollaza ? I'm not overly fussed - and I've seen it both ways elsewhere.

**Comment by zekiel** [comment]
@GuiltyDolphin  has this caused any problems you're noticing w/ other contributors? (trying to get a sense of how we should prioritize this potential change)

**Comment by GuiltyDolphin** [comment]
@zekiel Uhh, I haven't noticed anything that I could say is _caused_ by this - ofc. there is a fair bit of code that comes in that doesn't conform to the preferred style, but I doubt it is due to to this.

Just a thought I had when reading through.

**Comment by sahildua2305** [comment]
Being the one skimming through the docs quite regularly these days, I feel eligible enough to comment on this.

Replying to @zekiel I didn't feel any problem with the current format of examples (only good ones). And I strongly feel, this format is good (better than the suggested one, imho).

**Comment by GuiltyDolphin** [comment]
Looks like the general consensus is to stick; I'll close this as resolved :)
